### ISSUE TITLE
Trying to use elasticsearch from a koa app

### ISSUE THREAD

**Issue by softwarerero** [node-modules/thunkify-wrap#7]
I am new to koa and based on http://stackoverflow.com/questions/24914945/node-js-harmony-how-to-yield-elasticsearch-js-calls-using-koa?newreg=43ffa463c4654023b979639b234cd643 I thought thunkify-wrap might work. 

When the route in this server (https://gist.github.com/softwarerero/a8a2a2b7de5389dcc226) is hit I get this error:
`TypeError: Cannot read property 'request' of undefined
    at exec (/proj/2016/ruc/node_modules/elasticsearch/src/lib/client_action.js:351:19)
    at action (/proj/2016/ruc/node_modules/elasticsearch/src/lib/client_action.js:60:16)
    at thunk (/proj/2016/ruc/node_modules/thunkify-wrap/index.js:100:8)
    at genify (/proj/2016/ruc/node_modules/thunkify-wrap/genify.js:21:26)
    at [object Generator].next (native)
    at onFulfilled (/proj/2016/ruc/node_modules/koa/node_modules/co/index.js:65:19)
    at /proj/2016/ruc/node_modules/koa/node_modules/co/index.js:54:5
    at Object.co (/proj/2016/ruc/node_modules/koa/node_modules/co/index.js:50:10)
    at Object.toPromise (/proj/2016/ruc/node_modules/koa/node_modules/co/index.js:118:63)
    at next (/proj/2016/ruc/node_modules/koa/node_modules/co/index.js:99:29)
    at onFulfilled (/proj/2016/ruc/node_modules/koa/node_modules/co/index.js:69:7)
    at /proj/2016/ruc/node_modules/koa/node_modules/co/index.js:54:5
    at Object.co (/proj/2016/ruc/node_modules/koa/node_modules/co/index.js:50:10)
    at Object.createPromise (/proj/2016/ruc/node_modules/koa/node_modules/co/index.js:30:15)
    at Server.<anonymous> (/proj/2016/ruc/node_modules/koa/lib/application.js:132:8)
    at emitTwo (events.js:87:13)
    at Server.emit (events.js:172:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:529:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)`

Is there anything obvious I do wrong? I hope this is the right place to ask.

**Comment by dead-horse** [comment]
it looks like an error in `client_action.js`

**Comment by softwarerero** [comment]
Ok, thanks. I only wanted to be sure it has nothing to do with thunkify-wrap.
